# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parttype',
            old_name='price',
            new_name='defaultprice',
        ),
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='part',
            name='condition',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Refurbished'), (3, 'Used'), (4, 'For parts/not working')]),
        ),
    ]
