# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170920_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttype',
            name='defaultprice',
        ),
        migrations.AddField(
            model_name='parttype',
            name='condition',
            field=models.CharField(default='used', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parttype',
            name='price',
            field=models.CharField(default='100-500', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parttype',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
