# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170922_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='make',
            field=models.CharField(default='aeroplane', max_length=50),
            preserve_default=False,
        ),
    ]
