# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_parttype_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parttype',
            old_name='make',
            new_name='itemtype',
        ),
        migrations.AlterField(
            model_name='parttype',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
