# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20170923_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='partType',
        ),
        migrations.RemoveField(
            model_name='parttype',
            name='itemtype',
        ),
        migrations.RemoveField(
            model_name='parttype',
            name='name',
        ),
        migrations.AlterField(
            model_name='parttype',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
