# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20171004_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='location',
            field=models.CharField(default='Q mez', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parttype',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
