# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-21 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20180720_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='qanda',
            name='answer',
            field=models.TextField(default='No'),
            preserve_default=False,
        ),
    ]
