# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-22 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_qanda_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(default='The beginning of a song from the book of mormon called hello, it is a great song although the best is turn it off'),
            preserve_default=False,
        ),
    ]
