# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_blogpost_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='url',
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='a property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.ImageField(default='pretend this is an image', upload_to='properties', verbose_name='Picture of house'),
            preserve_default=False,
        ),
    ]
