# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-23 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20180723_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.ImageField(upload_to='properties/', verbose_name='Picture of a house'),
        ),
    ]
