# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-24 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20180723_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.AddField(
            model_name='property',
            name='rent',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
